name: Update README Stats

on:
  schedule:
    - cron: "0 */6 * * *"   # runs every 6 hours
  workflow_dispatch:

permissions:
  contents: write   # allow pushing changes

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update README (cache bust)
        run: |
          # Bust cache by updating timestamp in README
          sed -i "s/last_updated=.*/last_updated=$(date +%s)/" README.md || true

      - name: Commit & Push README
        run: |
          git config --global user.name "Nitesh-N-D"
         git config --global user.email "222636978+Nitesh-N-D@users.noreply.github.com" 
          git add README.md
          git commit -m "chore: update README [skip ci]" || echo "No changes to commit"
          git push
